name: tests

on:
  push:
    branches:
      - master

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04]

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y gdb xvfb
        python3 Tools/ssl/multissltests.py --steps=library --base-directory ${HOME}/multissl --openssl ${OPENSSL} >/dev/null 2>&1
        openssl version
