name: tests

on:
  push:
    branches:
      - master

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04]

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gdb xvfb openssl
        openssl version
        python3 --version
    - name: Run before_script
      run: |
        CFLAGS="${CFLAGS} -Og" ./configure --with-pydebug
        make -j4 regen-all
        make -j4
        make pythoninfo
